/**
 * LeagueService retrieves available leagues and realms.  For the
 * skeleton, it reads the cached JSON generated by the GitHub Action.
 */
export interface League {
  id: string;
  text: string;
  realm?: string;
}

export class LeagueService {
  static async getLeagues(): Promise<League[]> {
    try {
      const base = (import.meta as any).env?.BASE_URL || '/';
      const url = `${base}data/leagues.json`;
      const res = await fetch(url);
      if (!res.ok) return [];
      const data = await res.json();
      if (Array.isArray(data.result)) {
        return data.result.map((league: any) => ({
          id: league.id || league.text,
          text: league.text || league.id,
          realm: league.realm
        }));
      }
      return [];
    } catch (err) {
      return [];
    }
  }
}